BookWander/BookWander/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Wanderapp.urls', namespace='Wanderapp')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('account.urls', namespace='account')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('orders/', include('orders.urls', namespace='orders')),
    #path("search/", include("search.urls")),
]

if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BookWander/Wanderapp/urls.py
from django.urls import path
from . import views
from .views import GenreViewSet, BookViewSet, SearchGenres, SearchBooks
from django.urls import path, include
from rest_framework import routers


app_name = 'wanderapp'
router = routers.DefaultRouter()
router.register(r"genres", GenreViewSet)
router.register(r"books", BookViewSet)

urlpatterns = [
    # homepage path
    path('', views.homepage, name='homepage'),
    path('<slug:slug>', views.book_detail, name='book_detail'),  # path to book detail
    path('shop/<slug:genre_slug>', views.genre_list, name='genre_list'),
    #api get book, genre
    path('api/', include(router.urls)),
    #api search in books and genres
    path("search/genres/<str:query>/", SearchGenres.as_view()),
    path("search/books/<str:query>/", SearchBooks.as_view()),
]

BookWander/account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView

from . import views
from .forms import PwdResetConfirmForm, PwdResetForm, UserLoginForm



app_name = "account"

urlpatterns = [
    path("login/",
        auth_views.LoginView.as_view(
            template_name="account/registration/login.html", form_class=UserLoginForm
        ),
        name="login",
    ),
    path('logout/', views.logout_view, name='logout'),
    path("register/", views.account_register, name="register"),
    path("activate/<slug:uidb64>/<slug:token>/", views.account_activate, name="activate"
    ),
    # Reset password
    path("password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="account/user/password_reset_form.html",
            success_url="password_reset_email_confirm",
            email_template_name="account/user/password_reset_email.html",
            form_class=PwdResetForm,
        ),
        name="pwdreset",
    ),
    path("password_reset_confirm/<uidb64>/<token>",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="account/user/password_reset_confirm.html",
            success_url="/account/password_reset_complete/",
            form_class=PwdResetConfirmForm,
        ),
        name="password_reset_confirm",
    ),
    path("password_reset/password_reset_email_confirm/",
        TemplateView.as_view(template_name="account/user/reset_status.html"),
        name="password_reset_done",
    ),
    path("password_reset_complete/",
        TemplateView.as_view(template_name="account/user/reset_status.html"),
        name="password_reset_complete",
    ),
    # User dashboard
    path("dashboard/", views.dashboard, name="dashboard"),
    path("profile/edit/", views.edit_details, name="edit_details"),
    path("profile/delete_user/", views.delete_user, name="delete_user"),
    path("profile/delete_confirm/",
        TemplateView.as_view(template_name="account/user/delete_confirm.html"),
        name="delete_confirmation",
    ),
]

BookWander/api/urls.py
from django.urls import path
from .views import UsersApi, UserApi, UserCreateApi
from .views import BookCreateApi, BookApi, BooksApi, GenreApi

"""
"""
urlpatterns = [
    path('api/v1/users/profile/', UserCreateApi.as_view(), name="new_user"),
    path('api/v1/users/profile/<int:id>', UserApi.as_view(), name="user_profile"),
    path('api/v1/users/', UsersApi.as_view()),
    path('api/books/', BooksApi.as_view()),
    path('api/book/<int:id>', BookApi.as_view(), name="book_detail"),
    path('api/book/', BookCreateApi.as_view(), name="new_book"),
    path('api/books/categories/', GenreApi.as_view(), name="genre_list"),
]

BookWander/basket/urls.py
from django.urls import path

from . import views

app_name = "basket"

urlpatterns = [
    path("", views.basket_summary, name="basket_summary"),
    path("add/", views.basket_add, name="basket_add"),
    path("delete/", views.basket_delete, name="basket_delete"),
    path("update/", views.basket_update, name="basket_update"),
]

BookWander/Wanderapp/models.py
from django.db import models
from django.core.validators import MaxValueValidator
from django.db.models.query import QuerySet
from django.urls import reverse

# Create your models here.
class BookManager(models.Manager):
    def get_queryset(self):
        return super(BookManager, self).get_queryset().filter(in_stock=True)

# Genre table
class Genre(models.Model):
    genre_name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=255, unique=True)

    def get_absolute_url(self):
        return reverse('wanderapp:genre_list', args=[self.slug])

    def __str__(self):
        return f"{self.genre_name}"

# Books Table
class Book(models.Model):
    book_id = models.AutoField(primary_key=True)
    slug = models.SlugField(max_length=255)
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255)
    genre_name = models.ForeignKey(Genre, on_delete=models.CASCADE)
    publication_date = models.DateField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()
    cover_image_url = models.ImageField(upload_to='images/', default='images/default.png')
    in_stock = models.BooleanField(default=True)
    books = BookManager()

    def get_absolute_url(self):
        return reverse('wanderapp:book_detail', args=[self.slug])

    def __str__(self):
        return f"{self.title} {self.genre_name} {self.author}"

# moved the User Table into the 'account' app
""" 
# users table
class User(models.Model):
    user_id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=255)
    email = models.EmailField(max_length=50)
    password_hash = models.CharField(max_length=255)
    registration_date = models.DateTimeField()

    def __str__(self):
        return f'{self.username}'

# Orders Table
class Order(models.Model):
    order_id = models.AutoField(primary_key=True)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    order_date = models.DateTimeField()
    total_amount = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.order_id} {self.user_id}"

# Order_Items Table
class OrderItem(models.Model):
    order_item_id = models.AutoField(primary_key=True)
    order_id = models.ForeignKey(Order, on_delete=models.CASCADE)
    book_id = models.ForeignKey(Book, on_delete=models.CASCADE, related_name="book_title")
    quantity = models.IntegerField()
    unit_price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.order_item_id} {self.order_id} {self.book_id}"

# User_Preferences Table
class UserPreferences(models.Model):
    user_id = models.OneToOneField(User, primary_key=True, on_delete=models.CASCADE)
    genre_name = models.ForeignKey(Genre, on_delete=models.CASCADE)
    preferred_authors = models.CharField(max_length=255)
    notification_settings = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.user_id} {self.favorite_genre} {self.preferred_authors}"

# Reviews Table
class Review(models.Model):
    review_id = models.AutoField(primary_key=True)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    book_id = models.ForeignKey(Book, on_delete=models.CASCADE)
    rating = models.IntegerField(MaxValueValidator(5))
    comment = models.TextField()
    review_date = models.DateTimeField()

    def __str__(self):
        return f"{self.user_id} {self.book_id} rating:{self.rating} {self.comment}"

# Feedback Table
class Feedback(models.Model):
    feedback_id = models.AutoField(primary_key=True)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=255)
    message = models.TextField()
    feedback_date = models.DateTimeField()

    def __str__(self):
        return f"{self.feedback_id} {self.user_id} {self.message}"

# Shopping_Cart Table
class ShoppingCart(models.Model):
    cart_id = models.AutoField(primary_key=True)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.cart_id} {self.user_id}"

# Cart_Items Table
class CartItem(models.Model):
    cart_item_id = models.AutoField(primary_key=True)
    cart_id = models.ForeignKey(ShoppingCart, on_delete=models.CASCADE)
    book_id = models.ForeignKey(Book, on_delete=models.CASCADE)
    quantity = models.IntegerField()

    def __str__(self):
        return f"{self.cart_item_id} {self.cart_id} {self.book_id}"

# Subscriptions Table
class Subscription(models.Model):
    subscription_id = models.AutoField(primary_key=True)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    subscription_type = models.CharField(max_length=255)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()

# Images Table
class Image(models.Model):
    image_id = models.AutoField(primary_key=True)
    book_id = models.ForeignKey(Book, on_delete=models.CASCADE)
    image_url = models.URLField()
 """

BookWander/Wanderapp/forms.py
from django import forms 
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignupForm(UserCreationForm):
    class Meta:
        model = User 
        fields = ['username', 'password1']

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

BookWander/Wanderapp/views.py

import abc
from .models import Book, Genre
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from .serializers import GenreSerializer, BookSerializer
from .documents import GenreDocument, BookDocument
from rest_framework.views import APIView
from rest_framework.pagination import LimitOffsetPagination
from rest_framework import viewsets
from elasticsearch_dsl import Q
from rest_framework import status


def homepage(request):
    """View for homepage"""
    all_genres = Genre.objects.all()
    if request.method == "POST":
        req = request.POST['searched']
        #all_books = Book.books.filter(title=req)
        #new_req = "search/books/" + req + "/"
        quzry = Q("multi_match", query=req,
                  fields=["slug", "title", "author", "genre_name", "description"],
                  fuzziness="auto")
        search = BookDocument.search().query(quzry)
        all_books = search.execute()
        return render(request, './Wanderapp/homepage.html', {'books':all_books, 'genres':all_genres, 'is_search':1})
    else:
        all_books = Book.books.all()
        return render(request, './Wanderapp/homepage.html', {'books':all_books, 'genres':all_genres, 'is_search':0})


# view for a specific book
def book_detail(request, slug):
    """provides the detail of a single book"""
    book = get_object_or_404(Book, slug=slug, in_stock=True)
    return render(request, './Wanderapp/books/detail.html', {'book':book}) 

# view for all books in a genre
#@login_required
def genre_list(request, genre_slug):
    """shows books by genre"""
    genre = get_object_or_404(Genre, slug=genre_slug)
    books = Book.books.filter(genre_name=genre)
    return render(request, './Wanderapp/books/genre.html', {"genre":genre, 'book': books})


def search_all(request):
    
    """
    all_genres = Genre.objects.all()
    if request.method == "POST":
        req = request.POST['searched']
        all_books = Book.books.filter(title=req)
        return render(request, './Wanderapp/homepage.html', {'books':all_books, 'genres':all_genres})
    else:
        return render(request, './Wanderapp/homepage.html', {'books':None, 'genres':all_genres})
    """
    return render(status=status.HTTP_204_NO_CONTENT)


class GenreViewSet(viewsets.ModelViewSet):
    serializer_class = GenreSerializer
    queryset = Genre.objects.all()


class BookViewSet(viewsets.ModelViewSet):
    serializer_class = BookSerializer
    queryset = Book.books.all()
    
    
class PaginatedElasticSearchAPIView(APIView, LimitOffsetPagination):
    serializer_class = None
    document_class = None

    @abc.abstractmethod
    def generate_q_expression(self, query):
        """"""

    def get(self, request, query):
        try:
            q = self.generate_q_expression(query)
            s = self.document_class.search().query(q)
            r = s.execute()
            print(f"Found {r.hits.total.value} hit(s) for query: '{query}'")
            rslt = self.paginate_queryset(r, request, view=self)
            serializer = self.serializer_class(rslt, many=True)
            return self.get_paginated_response(serializer.data)
        except Exception as e:
            return HttpResponse(e, status=500)


class SearchGenres(PaginatedElasticSearchAPIView):
    """fuzzy searches in genres names.
    """
    document_class = GenreDocument
    serializer_class = GenreSerializer

    def generate_q_expression(self, query):
        return Q("multi_match", query=query,
                fields=["genre_name"], fuzziness="auto")
        

class SearchBooks(PaginatedElasticSearchAPIView):
    """fuzzy searches in Books.
    """
    document_class = BookDocument
    serializer_class = BookSerializer

    def generate_q_expression(self, query):
        return Q("multi_match",
                 query=query,
                 fields=[
                     "slug", "title", "author",
                     "genre_name",
                     "description"], fuzziness="auto")

BookWander/templates/Wanderapp/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>{% block title %}BookWander{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous">
    </script>
    <link
      href="https://cdn.jsdelivr.net/npm/remixicon@3.5.0/fonts/remixicon.css"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'BookWander/css/base.css' %}">
    <link rel="stylesheet" href="{% static 'basket/css/basket.css' %}">
</head>

<body>
    <header class="pb-3">
        <nav class="navbar navbar-expand-md navbar-light bg-white border-bottom">
            <div class="container-fluid px-md-4">
                <div class="d-flex w-100 navbar-collapse">
                    <a class="navbar-brand d-flex-inline" href="/">
                        BookWander
                        <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" fill="currentColor"
                            class="bi bi-asterisk" viewBox="0 0 16 16">
                            <path
                                d="M8 0a1 1 0 0 1 1 1v5.268l4.562-2.634a1 1 0 1 1 1 1.732L10 8l4.562 2.634a1 1 0 1 1-1 1.732L9 9.732V15a1 1 0 1 1-2 0V9.732l-4.562 2.634a1 1 0 1 1-1-1.732L6 8 1.438 5.366a1 1 0 0 1 1-1.732L7 6.268V1a1 1 0 0 1 1-1z" />
                        </svg>
                    </a>
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle d-none d-md-block fw500" href="#" id="navbarDropdown"
                                role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Library
                                <i class="ps-1"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                        fill="currentColor" class="bi bi-chevron-down" viewBox="0 0 16 16">
                                        <path fill-rule="evenodd"
                                            d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z" />
                                    </svg></i>
                            </a>
                            <ul class="dropdown-menu rounded-0 border-0" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url "wanderapp:homepage" %}">All</a></li>
                                {% for g in genres %}
                                <li {% if genre.slug == g.slug %}class="selected" {% endif %}>
                                    <a class="dropdown-item" href="{{ g.get_absolute_url }}">{{ g.genre_name|title }}</a>
                                </li>
                                {% endfor %}
                            </ul>
                        </li>
                    </ul>
                    
                    <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false"
                        aria-label="Toggle navigation">
                        <div>
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                                class="bi bi-list" viewBox="0 0 16 16">
                                <path fill-rule="evenodd"
                                    d="M2.5 11.5A.5.5 0 0 1 3 11h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4A.5.5 0 0 1 3 7h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4A.5.5 0 0 1 3 3h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z" />
                            </svg>
                        </div>
                        <span class="fs15 fw500">Shop</span>
                    </button>

                    {% if user.is_authenticated %}
                    <a type="button" role="button" href="{% url 'account:logout' %}"
                        class="btn btn-outline-secondary border-0 basket-btn">
                        <div>
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                                class="bi bi-door-closed" viewBox="0 0 16 16">
                                <path
                                    d="M3 2a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v13h1.5a.5.5 0 0 1 0 1h-13a.5.5 0 0 1 0-1H3V2zm1 13h8V2H4v13z" />
                                <path d="M9 9a1 1 0 1 0 2 0 1 1 0 0 0-2 0z" />
                            </svg>
                        </div>
                        <span class="fs15 fw500">Logout</span>
                    </a>
                    {% else %}
                    <a type="button" role="button" href="{% url 'account:login' %}"
                        class="btn btn-outline-secondary border-0 basket-btn">
                        <div>
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                                class="bi bi-door-closed" viewBox="0 0 16 16">
                                <path
                                    d="M3 2a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v13h1.5a.5.5 0 0 1 0 1h-13a.5.5 0 0 1 0-1H3V2zm1 13h8V2H4v13z" />
                                <path d="M9 9a1 1 0 1 0 2 0 1 1 0 0 0-2 0z" />
                            </svg>
                        </div>
                        <span class="fs15 fw500">Login</span>
                    </a>
                    {% endif %}


                    <a type="button" role="button" href="{% url 'account:dashboard' %}"
                        class="btn btn-outline-secondary border-0 basket-btn">
                        <div>
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                                class="bi bi-person" viewBox="0 0 16 16">
                                <path
                                    d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z" />
                            </svg>
                        </div>
                        <span class="fs15 fw500">Account</span>
                    </a>

                    <a type="button" role="button" href="{% url 'basket:basket_summary' %}"
                        class="btn btn-outline-secondary border-0 basket-btn">

                        {% with total_qty=basket|length %}
                        <div id="basket-qty" class="basket-qty">
                            {% if total_qty > 0 %}
                            {{ total_qty }}
                            {% else %}
                            0
                            {% endif %}
                        </div>
                        {% endwith %}
                        <div>
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                                class="bi bi-cart3" viewBox="0 0 16 16">
                                <path
                                    d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                            </svg>
                        </div>
                        <span class="fs15 fw500">Basket</span>
                    </a>
                </div>
                <div class="d-md-none d-lg-none d-xl-none">
                    <div class="collapse navbar-collapse" id="navbarCollapse">
                        <ul class="navbar-nav me-auto mb-2 mb-md-0">
                            <li><a class="dropdown-item" href="{% url 'wanderapp:homepage' %}">All</a></li>
                            {% for g in genres %}
                            <li {% if genre.slug == g.slug %}class="selected" {% endif %}>
                                <a class="dropdown-item" href="{{ g.get_absolute_url }}">{{ g.genre_name|title }}</a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <form class="d-flex w-50" method=POST action="{% url 'wanderapp:homepage' %}">
                    {% csrf_token %}
                    <input class="form-control me-2" type="search" placeholder="Search ..."
                        aria-label="Search" name="searched">
                    <button class="btn btn-outline-secondary" type="submit">Search</button>
                </form>
            </div>
        </nav>
    </header>

    <div id="content">{% block content %} {% endblock %}</div>

    <footer class="container py-5 footer">
        <hr>
        <div class="row pt-4">
            <div class="col-12 col-md">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                    class="bi bi-asterisk" viewBox="0 0 16 16">
                    <path
                        d="M8 0a1 1 0 0 1 1 1v5.268l4.562-2.634a1 1 0 1 1 1 1.732L10 8l4.562 2.634a1 1 0 1 1-1 1.732L9 9.732V15a1 1 0 1 1-2 0V9.732l-4.562 2.634a1 1 0 1 1-1-1.732L6 8 1.438 5.366a1 1 0 0 1 1-1.732L7 6.268V1a1 1 0 0 1 1-1z" />
                </svg>
                <small class="d-block mb-3 text-muted">&copy; 2024-2025</small>
            </div>
            <div class="col-6 col-md fs15">
                <h5>Features</h5>
                <ul class="list-unstyled">
                    <li><a class="link-secondary text-decoration-none" href="#">Cool stuff</a></li>
                    <li><a class="link-secondary text-decoration-none" href="#">Random feature</a></li>
                    <li><a class="link-secondary text-decoration-none" href="#">Team feature</a></li>
                    <li><a class="link-secondary text-decoration-none" href="#">Stuff for developers</a></li>
                    <li><a class="link-secondary text-decoration-none" href="#">Another one</a></li>
                    <li><a class="link-secondary text-decoration-none" href="#">Last time</a></li>
                </ul>
            </div>
            <div class="col-6 col-md fs15">
                <h5>Resources</h5>
                <ul class="list-unstyled">
                    <li><a class="link-secondary text-decoration-none" href="#">Resource name</a></li>
                    <li><a class="link-secondary text-decoration-none" href="#">Resource</a></li>
                    <li><a class="link-secondary text-decoration-none" href="#">Another resource</a></li>
                    <li><a class="link-secondary text-decoration-none" href="#">Final resource</a></li>
                </ul>
            </div>
            <div class="col-6 col-md fs15">
                <h5>Resources</h5>
                <ul class="list-unstyled">
                    <li><a class="link-secondary text-decoration-none" href="#">Business</a></li>
                    <li><a class="link-secondary text-decoration-none" href="#">Education</a></li>
                    <li><a class="link-secondary text-decoration-none" href="#">Government</a></li>
                    <li><a class="link-secondary text-decoration-none" href="#">Gaming</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>About</h5>
                <ul class="list-unstyled">
                    <li><a class="link-secondary text-decoration-none" href="#">Team</a></li>
                    <li><a class="link-secondary text-decoration-none" href="#">Locations</a></li>
                    <li><a class="link-secondary text-decoration-none" href="#">Privacy</a></li>
                    <li><a class="link-secondary text-decoration-none" href="#">Terms</a></li>
                </ul>
            </div>
        </div>
    </footer>
</body>

</html>

BookWander/templates/Wanderapp/homepage.html
{% extends "./base.html" %}
{% load static %}
{% block title %}BookWander{% endblock %}
{% block content %}
<main>
  <div class="container">
    <div class="container">
      <div class="row">
        <div class="album py-5">
          <div class="pb-3">
            {% if is_search > 0 %}
            <h1 class="h3">Results</h1>
            {% else %}
            <h1 class="h3">Popular</h1>
            {% endif %}
          </div>
          <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
            {% if not books %}
            <h4>No Books found.</h4>
            {% else %}
            {% for book in books %}
            <div class="col">
              <div class="card border-0">
                {% if is_search > 0 %}
                <img class="img-fluid" alt="Responsive image" src="{{ book.cover_image_url }}">
                {% else %}
                <img class="img-fluid" alt="Responsive image" src="{{ book.cover_image_url.url }}">
                {% endif %}
                
                <div class="card-body px-0">
                  <p class="card-text">
                    <a class="text-dark text-decoration-none"
                      href="{{ book.get_absolute_url }}">{{ book.title|slice:":50" }}...</a>
                  </p>
                  <div class="fw-bold">£{{book.price}}</div>
                </div>
              </div>
            </div>
            {% endfor %}
            {% endif %}
          </div>
        </div>
      </div>
    </div>
</main>
{% endblock %}