BookWander/BookWander/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Wanderapp.urls', namespace='Wanderapp')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('account.urls', namespace='account')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('orders/', include('orders.urls', namespace='orders')),
    #path("search/", include("search.urls")),
]

if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BookWander/Wanderapp/urls.py
from django.urls import path
from . import views
from .views import GenreViewSet, BookViewSet, SearchGenres, SearchBooks
from django.urls import path, include
from rest_framework import routers


app_name = 'wanderapp'
router = routers.DefaultRouter()
router.register(r"genres", GenreViewSet)
router.register(r"books", BookViewSet)

urlpatterns = [
    # homepage path
    path('', views.homepage, name='homepage'),
    path('<slug:slug>', views.book_detail, name='book_detail'),  # path to book detail
    path('shop/<slug:genre_slug>', views.genre_list, name='genre_list'),
    #api get book, genre
    path('api/', include(router.urls)),
    #api search in books and genres
    path("search/genres/<str:query>/", SearchGenres.as_view()),
    path("search/books/<str:query>/", SearchBooks.as_view()),
]

BookWander/api/urls.py
from django.urls import path
from .views import UsersApi, UserApi, UserCreateApi
from .views import BookCreateApi, BookApi, BooksApi, GenreApi

"""
"""
urlpatterns = [
    path('api/v1/users/profile/', UserCreateApi.as_view(), name="new_user"),
    path('api/v1/users/profile/<int:id>', UserApi.as_view(), name="user_profile"),
    path('api/v1/users/', UsersApi.as_view()),
    path('api/books/', BooksApi.as_view()),
    path('api/book/<int:id>', BookApi.as_view(), name="book_detail"),
    path('api/book/', BookCreateApi.as_view(), name="new_book"),
    path('api/books/categories/', GenreApi.as_view(), name="genre_list"),
]

BookWander/basket/urls.py
from django.urls import path

from . import views

app_name = "basket"

urlpatterns = [
    path("", views.basket_summary, name="basket_summary"),
    path("add/", views.basket_add, name="basket_add"),
    path("delete/", views.basket_delete, name="basket_delete"),
    path("update/", views.basket_update, name="basket_update"),
]

BookWander/Wanderapp/models.py
from django.db import models
from django.core.validators import MaxValueValidator
from django.db.models.query import QuerySet
from django.urls import reverse

# Create your models here.
class BookManager(models.Manager):
    def get_queryset(self):
        return super(BookManager, self).get_queryset().filter(in_stock=True)

# Genre table
class Genre(models.Model):
    genre_name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=255, unique=True)

    def get_absolute_url(self):
        return reverse('wanderapp:genre_list', args=[self.slug])

    def __str__(self):
        return f"{self.genre_name}"

# Books Table
class Book(models.Model):
    book_id = models.AutoField(primary_key=True)
    slug = models.SlugField(max_length=255)
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255)
    genre_name = models.ForeignKey(Genre, on_delete=models.CASCADE)
    publication_date = models.DateField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()
    cover_image_url = models.ImageField(upload_to='images/', default='images/default.png')
    in_stock = models.BooleanField(default=True)
    books = BookManager()

    def get_absolute_url(self):
        return reverse('wanderapp:book_detail', args=[self.slug])

    def __str__(self):
        return f"{self.title} {self.genre_name} {self.author}"

# moved the User Table into the 'account' app
""" 
# users table
class User(models.Model):
    user_id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=255)
    email = models.EmailField(max_length=50)
    password_hash = models.CharField(max_length=255)
    registration_date = models.DateTimeField()

    def __str__(self):
        return f'{self.username}'

# Orders Table
class Order(models.Model):
    order_id = models.AutoField(primary_key=True)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    order_date = models.DateTimeField()
    total_amount = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.order_id} {self.user_id}"

# Order_Items Table
class OrderItem(models.Model):
    order_item_id = models.AutoField(primary_key=True)
    order_id = models.ForeignKey(Order, on_delete=models.CASCADE)
    book_id = models.ForeignKey(Book, on_delete=models.CASCADE, related_name="book_title")
    quantity = models.IntegerField()
    unit_price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.order_item_id} {self.order_id} {self.book_id}"

# User_Preferences Table
class UserPreferences(models.Model):
    user_id = models.OneToOneField(User, primary_key=True, on_delete=models.CASCADE)
    genre_name = models.ForeignKey(Genre, on_delete=models.CASCADE)
    preferred_authors = models.CharField(max_length=255)
    notification_settings = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.user_id} {self.favorite_genre} {self.preferred_authors}"

# Reviews Table
class Review(models.Model):
    review_id = models.AutoField(primary_key=True)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    book_id = models.ForeignKey(Book, on_delete=models.CASCADE)
    rating = models.IntegerField(MaxValueValidator(5))
    comment = models.TextField()
    review_date = models.DateTimeField()

    def __str__(self):
        return f"{self.user_id} {self.book_id} rating:{self.rating} {self.comment}"

# Feedback Table
class Feedback(models.Model):
    feedback_id = models.AutoField(primary_key=True)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=255)
    message = models.TextField()
    feedback_date = models.DateTimeField()

    def __str__(self):
        return f"{self.feedback_id} {self.user_id} {self.message}"

# Shopping_Cart Table
class ShoppingCart(models.Model):
    cart_id = models.AutoField(primary_key=True)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.cart_id} {self.user_id}"

# Cart_Items Table
class CartItem(models.Model):
    cart_item_id = models.AutoField(primary_key=True)
    cart_id = models.ForeignKey(ShoppingCart, on_delete=models.CASCADE)
    book_id = models.ForeignKey(Book, on_delete=models.CASCADE)
    quantity = models.IntegerField()

    def __str__(self):
        return f"{self.cart_item_id} {self.cart_id} {self.book_id}"

# Subscriptions Table
class Subscription(models.Model):
    subscription_id = models.AutoField(primary_key=True)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    subscription_type = models.CharField(max_length=255)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()

# Images Table
class Image(models.Model):
    image_id = models.AutoField(primary_key=True)
    book_id = models.ForeignKey(Book, on_delete=models.CASCADE)
    image_url = models.URLField()
 """

BookWander/Wanderapp/forms.py
from django import forms 
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignupForm(UserCreationForm):
    class Meta:
        model = User 
        fields = ['username', 'password1']

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

BookWander/Wanderapp/views.py

import abc
from .models import Book, Genre
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from .serializers import GenreSerializer, BookSerializer
from .documents import GenreDocument, BookDocument
from rest_framework.views import APIView
from rest_framework.pagination import LimitOffsetPagination
from rest_framework import viewsets
from elasticsearch_dsl import Q
from rest_framework import status


def homepage(request):
    """View for homepage"""
    all_genres = Genre.objects.all()
    if request.method == "POST":
        req = request.POST['searched']
        #all_books = Book.books.filter(title=req)
        #new_req = "search/books/" + req + "/"
        quzry = Q("multi_match", query=req,
                  fields=["slug", "title", "author", "genre_name", "description"],
                  fuzziness="auto")
        search = BookDocument.search().query(quzry)
        all_books = search.execute()
        return render(request, './Wanderapp/homepage.html', {'books':all_books, 'genres':all_genres, 'is_search':1})
    else:
        all_books = Book.books.all()
        return render(request, './Wanderapp/homepage.html', {'books':all_books, 'genres':all_genres, 'is_search':0})


# view for a specific book
def book_detail(request, slug):
    """provides the detail of a single book"""
    book = get_object_or_404(Book, slug=slug, in_stock=True)
    return render(request, './Wanderapp/books/detail.html', {'book':book}) 

# view for all books in a genre
#@login_required
def genre_list(request, genre_slug):
    """shows books by genre"""
    genre = get_object_or_404(Genre, slug=genre_slug)
    books = Book.books.filter(genre_name=genre)
    return render(request, './Wanderapp/books/genre.html', {"genre":genre, 'book': books})


def search_all(request):
    
    """
    all_genres = Genre.objects.all()
    if request.method == "POST":
        req = request.POST['searched']
        all_books = Book.books.filter(title=req)
        return render(request, './Wanderapp/homepage.html', {'books':all_books, 'genres':all_genres})
    else:
        return render(request, './Wanderapp/homepage.html', {'books':None, 'genres':all_genres})
    """
    return render(status=status.HTTP_204_NO_CONTENT)


class GenreViewSet(viewsets.ModelViewSet):
    serializer_class = GenreSerializer
    queryset = Genre.objects.all()


class BookViewSet(viewsets.ModelViewSet):
    serializer_class = BookSerializer
    queryset = Book.books.all()
    
    
class PaginatedElasticSearchAPIView(APIView, LimitOffsetPagination):
    serializer_class = None
    document_class = None

    @abc.abstractmethod
    def generate_q_expression(self, query):
        """"""

    def get(self, request, query):
        try:
            q = self.generate_q_expression(query)
            s = self.document_class.search().query(q)
            r = s.execute()
            print(f"Found {r.hits.total.value} hit(s) for query: '{query}'")
            rslt = self.paginate_queryset(r, request, view=self)
            serializer = self.serializer_class(rslt, many=True)
            return self.get_paginated_response(serializer.data)
        except Exception as e:
            return HttpResponse(e, status=500)


class SearchGenres(PaginatedElasticSearchAPIView):
    """fuzzy searches in genres names.
    """
    document_class = GenreDocument
    serializer_class = GenreSerializer

    def generate_q_expression(self, query):
        return Q("multi_match", query=query,
                fields=["genre_name"], fuzziness="auto")
        

class SearchBooks(PaginatedElasticSearchAPIView):
    """fuzzy searches in Books.
    """
    document_class = BookDocument
    serializer_class = BookSerializer

    def generate_q_expression(self, query):
        return Q("multi_match",
                 query=query,
                 fields=[
                     "slug", "title", "author",
                     "genre_name",
                     "description"], fuzziness="auto")

BookWander/templates/Wanderapp/books/detail.html
{% extends "Wanderapp/base.html" %}
{% load static %}
{% block title %}
{{ book.name }}
{% endblock %}
{% block content %}


<main class="pt-2">

  <div class="container" style="max-width: 1000px">

    <div class="row g-3">
        <div class="col-12 d-flex justify-content-between">

        </div>

        <div class="col-md-5 ps-3 col-lg-5 order-md-last p-0 order-1">
            <div class="d-grid gap-2">

            <div class="d-flex d-flex-inline justify-content-between">
            <div><span class="h3">£{{ book.price }}</span><p class="text-muted">includes tax</p></div>
                   <div class="">
                                <label for="select">Qty</label>
                                <select id="select" class="h6" style="width:50px;height:40px;">
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                                </select>
                    </div>
            </div>
            <hr>
            <button type="button" id="add-button" value="{{book.book_id}}" class="btn btn-success fw500">Add to basket</button>
            <button type="button" id="add-button" value="{{book.book_id}}" class="btn btn-light fw500">Add to Favorites</button>
            </div>
        </div>

        <div class="col-md-7 col-lg-7 p-0">

        

            <div class="card mb-3 border-0">
            <div class="row g-0">
                <div class="col-md-12">
                    <div class="card-body p-1">
                        <h1 class="mb-0 h2 pe-4 pb-4">{{ book.title }}</h1>
                        <div class="bg-light"><img class="img-fluid mx-auto d-block" width="200px" alt="Responsive image" src="{{ book.cover_image_url.url }}"> </div>
                    </div>
                    
                </div>
            </div>
            </div>
        </div>
    </div>
  </div>
</main>

<script>
    $(document).on('click', '#add-button', function (e) {
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '{% url "basket:basket_add" %}',
            data: {
                bookid: $('#add-button').val(),
                bookqty: $('#select option:selected').text(),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },
            success: function (json) {
               document.getElementById("basket-qty").innerHTML = json.qty
            },
            error: function (xhr, errmsg, err) {}
        });
    })
</script>

{% endblock %}

BookWander/templates/Wanderapp/books/genre.html
{% extends "../base.html" %}
{% load static %}
{% block title %}
{% if genre %}{{ genre.name }}{% else %}Books{% endif %}
{% endblock %}
{% block content %}

<main>
  <div class="container">
    <div class="row">
      <div class="album py-5">
        <div class="pb-3"><h1 class="h3">Popular</h1></div>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
          {% for books in book %}
          <div class="col">
            <div class="card border-0">
              <img class="img-fluid" alt="Responsive image" src="{{ books.cover_image_url.url }}">
              <div class="card-body px-0">
                <p class="card-text">
                  <a class="text-dark text-decoration-none"
                    href="{{ books.get_absolute_url }}">{{ books.title }}</a>
                </p>
                <div class="d-flex justify-content-between align-items-center">
                  <small class="text-muted">£{{books.price}}</small>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}